version: "3.8"
services:
  mysql:
    image: mysql:8.3.0
    container_name: splitwise-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: splitwise
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysqldata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysqldata: